runtime: python38

handlers:
- url: /
  static_files: static/public/index.html
  upload: static/public/index.html

- url: /(.*)/
  static_files: static/public/\1/index.html
  upload: static/public/.*/index.html

- url: /(.*)
  static_files: static/public/\1
  upload: static/public/(.*)
